spring:
  application:
    name: eureka-server-cluster
  profiles: peer3
server:
  port: 6003
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      # 向peer1 peer2节点注册自己
      defaultZone: http://peer1:6001/eureka,http://peer2:6002/eureka