server:
  port: 9002
spring:
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1.
  h2:
    enabled: true
    path: "/h2-console"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true