server:
  port: 9021

spring:
  application:
    name: ddd-authentication
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      springframework:
        security: INFO