package org.ddd.fundamental.workprocess.value.time;

public enum WorkProcessTimeEvent {

    // WORK_PROCESS_TRANSFER ---> WORK_PROCESS_TRANSFER_OVER
    WORK_PROCESS_TRANSFER_OVER_EVENT,

    // WORK_PROCESS_OFFLINE ---> WORK_PROCESS_TRANSFER
    WORK_PROCESS_TRANSFER_EVENT,

    // WORK_PROCESS_FINISHED ---> WORK_PROCESS_OFFLINE
    WORK_PROCESS_OFFLINE_EVENT,

    // WORK_PROCESS_RUNNING ---> WORK_PROCESS_FINISHED
    // WORK_PROCESS_INTERRUPTED --->WORK_PROCESS_FINISHED
    // WORK_PROCESS_CHECKED ---> WORK_PROCESS_FINISHED
    WORK_PROCESS_FINISH_EVENT,

    // WORK_PROCESS_INTERRUPTED --->WORK_PROCESS_RUNNING
    // WORK_PROCESS_CHECKED ---> WORK_PROCESS_RUNNING
    WORK_PROCESS_RESTART_EVENT,

    // WORK_PROCESS_INTERRUPTED ---> WORK_PROCESS_CHECKED
    WORK_PROCESS_CHECK_EVENT,

    // WORK_PROCESS_RUNNING ---> WORK_PROCESS_INTERRUPTED
    WORK_PROCESS_INTERRUPT_EVENT,

    //INIT ---> LINE_CHANGED
    CHANGE_LINE_START_EVENT,

    // INIT ---> WORK_PROCESS_RUNNING or
    // LINE_CHANGED ---> WORK_PROCESS_RUNNING
    WORK_PROCESS_START_EVENT;



}
