server:
  port: 9004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/equipment?useSSL=false&pinGlobalTxToPhysicalConnection=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.ddd.fundamental.equipment.config.CustomMySQLDialect
  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug

