server:
  port: 9007
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bom?useSSL=false&pinGlobalTxToPhysicalConnection=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:29092
  redis:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000
    sentinel:
      master: mymaster
      nodes:
        - 10.0.0.118:26379
        - 10.0.0.118:26380
        - 10.0.0.118:26381
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug

