server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work_order?useSSL=false&pinGlobalTxToPhysicalConnection=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:29092

