server:
  port: 6033
spring:
  application:
    name: ddd-conditional
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      jdbc:
        batch_size: 4
      order_inserts: true
      order_updates: true
      generate_statistics: true
      globally_quoted_identifiers: true