spring:
  application:
    name: spring-cloud-module-user
#  security:
#    user:
#      name: yun900800
#      password: 123456
  redis:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000
    sentinel:
      master: mymaster
      nodes:
        - 10.0.0.118:26379
        - 10.0.0.118:26380
        - 10.0.0.118:26381
server:
  port: 16000
eureka:
  client:
    register-with-eureka: true #本微服务为服务生产者，需要将自己注册到服务注册中心
    fetch-registry: true  #本微服务为服务消费者，需要到服务注册中心搜索服务
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:6001/eureka/,http://peer2:6002/eureka/,http://peer3:6003/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

#management:
#  server:
#    port: 6500
#    address: localhost
#  endpoints:
#    web:
#      exposure:
#        # 开放所有端点
#        include: '*'
#  security:
#    enabled: false
ddd:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 10.0.0.118:26379
        - 10.0.0.118:26380
        - 10.0.0.118:26381
